
import { listRequestsType } from "@/types";

export const requests: listRequestsType[] = [
    {
      id: 1,
      user: "gavrilov",
      topic: "электронная почта",
      numberUser: 95708,
      dateCreate: "20.05.2024 15:22",
      dateUpdate: "20.05.2024 17:22",
      deadline: "21.05.2024 15:22",
      status: "В работе",
      awaitingResponse: false,
      description: "Прошу сделать переадресацию на время отпуска",
      solution: "",
      service: "Интернет",
      compositionService: "Почта",
      sign: "Ожидает ответа",
    },
    {
      id: 2,
      user: "gavrilov",
      topic: "Установка платформы",
      numberUser: 95802,
      dateCreate: "22.05.2024 11:03",
      dateUpdate: "22.05.2024 11:03",
      deadline: "23.05.2024 11:03",
      status: "Зарегистрировано",
      awaitingResponse: false,
      description: "Прошу установить платформу 8.3.24",
      solution: "",
      service: "Поддержка рабочих мест",
      compositionService: "Настройка ПО",
      sign: "",
    },
    {
      id: 3,
      user: "gavrilov",
      topic: "Подключение к сети",
      numberUser: 95803,
      dateCreate: "24.05.2024 9:41",
      dateUpdate: "24.05.2024 11:41",
      deadline: "25.05.2024 9:41",
      status: "На согласовании",
      awaitingResponse: false,
      description: "Нужен доступ к serversoft",
      solution: "",
      service: "Интернет",
      compositionService: "Доступ",
      sign: "Ожидает ответа",
    },
    {
      id: 4,
      user: "gavrilov",
      topic: "Установка ПО на ПК",
      numberUser: 95804,
      dateCreate: "24.05.2024 12:30",
      dateUpdate: "24.05.2024 12:30",
      deadline: "25.05.2024 12:30",
      status: "Выполнено. Требует подтверждения",
      awaitingResponse: true,
      description: "Для нового сотрудника нужна IDE",
      solution: "Софт установлен",
      service: "Поддержка рабочих мест",
      compositionService: "Настройка ПО",
      sign: "Ожидает ответа",
    },
    {
      id: 5,
      user: "gavrilov",
      topic: "Проблема с сетью",
      numberUser: 95901,
      dateCreate: "25.05.2024 10:07",
      dateUpdate: "26.05.2024 9:00",
      deadline: "26.05.2024 10:07",
      status: "Зарегистрировано",
      awaitingResponse: false,
      description: "Не заходит на внешние сайты при включенном впн",
      solution: "",
      service: "Интернет",
      compositionService: "Доступ",
      sign: "",
    },
    {
      id: 6,
      user: "gavrilov",
      topic: "Установка проектора",
      numberUser: 95902,
      dateCreate: "27.05.2024 14:11",
      dateUpdate: "27.05.2024 14:11",
      deadline: "28.05.2024 14:11",
      status: "Закрыто",
      awaitingResponse: false,
      description: "В ауд. 312",
      solution: "Проектор установлен",
      service: "Поддержка рабочих мест",
      compositionService: "Настройка оборудования",
      sign: "",
    },
    {
      id: 7,
      user: "gavrilov",
      topic: "Активация Office",
      numberUser: 95903,
      dateCreate: "29.05.2024 13:15",
      dateUpdate: "29.05.2024 13:15",
      deadline: "30.05.2024 13:15",
      status: "На согласовании",
      awaitingResponse: true,
      description: "Требуется офис на выездном ноутбуке",
      solution: "Активирован 2016",
      service: "Поддержка рабочих мест",
      compositionService: "Настройка ПО",
      sign: "",
    },
    {
      id: 8,
      user: "gavrilov",
      topic: "Замена картриджа",
      numberUser: 95918,
      dateCreate: "29.05.2024 16:10",
      dateUpdate: "29.05.2024 16:10",
      deadline: "30.05.2024 16:10",
      status: "В работе",
      awaitingResponse: false,
      description: "В каб. 111",
      solution: "",
      service: "Поддержка рабочих мест",
      compositionService: "Настройка оборудования",
      sign: "",
    },
  ];